version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
        - npm install
        - npm run build-storybook
        - aws s3 sync storybook-static s3://storybook-trial-jeremywang  --delete